# Set base OS
# FROM ubuntu:latest 
FROM ubuntu:24.04


# Remove default user ubuntu. Assumes using 23.04 or newer (no checks are present)
RUN touch /var/mail/ubuntu \
    && chown ubuntu /var/mail/ubuntu \
    && userdel -r ubuntu


# Set user of the container
ARG USERNAME=vscode	
ARG USER_UID=1000
ARG USER_GID=${USER_UID}
RUN groupadd --gid ${USER_GID} ${USERNAME} \
    && useradd --uid ${USER_UID} --gid ${USER_GID} -m ${USERNAME}

	
# Used to persist bash history as per https://code.visualstudio.com/remote/advancedcontainers/persist-bash-history
RUN SNIPPET="export PROMPT_COMMAND='history -a' && export HISTFILE=/commandhistory/.bash_history" \
    && mkdir /commandhistory \
    && touch /commandhistory/.bash_history \
    && chown -R $USERNAME /commandhistory \
    && echo "$SNIPPET" >> "/home/$USERNAME/.bashrc"


# Set locale
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y locales
RUN sed -i -e 's/# en_GB.UTF-8 UTF-8/en_GB.UTF-8 UTF-8/' /etc/locale.gen && \
    dpkg-reconfigure --frontend=noninteractive locales && \
    update-locale LANG=en_GB.UTF-8
ENV LANG=en_GB.UTF-8 


# Install git, C/C++, and Python and requirements. (Rust is installed below)
USER root
RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \ 
    && apt-get update && apt-get -y install --no-install-recommends \
         wget apt-transport-https software-properties-common \
         git-all expect \
         curl \
         python3.12 python3.12-venv python3-pip python3.12-dev \
         jq \
         vim \
         dos2unix \
    && apt-get autoremove -y && apt-get clean -y && rm -rf /var/lib/apt/lists/* \
ENV RUNNING_IN_DOCKER=true


# Install UV
ARG PYTHON_VERSION=3.14
COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv
ENV UV_LINK_MODE=copy \
    UV_PYTHON=python${PYTHON_VERSION} \
    UV_PYTHON_DOWNLOADS=automatic


# Install Python environment as used in paper
ARG TARGETARCH
RUN set -eux; \
    case "${TARGETARCH}" in \
      amd64) CONDA_ARCH="x86_64" ;; \
      arm64) CONDA_ARCH="aarch64" ;; \
      *) echo "Unsupported TARGETARCH=${TARGETARCH}" >&2; exit 1 ;; \
    esac; \
    mkdir -p /opt/miniconda; \
    wget -O /tmp/miniconda.sh "https://repo.anaconda.com/miniconda/Miniconda3-py37_23.1.0-1-Linux-${CONDA_ARCH}.sh";\
    bash /tmp/miniconda.sh -b -u -p /opt/miniconda \
    rm -f /tmp/miniconda.sh



USER vscode
ENV PATH="/opt/miniconda/bin:${PATH}"
WORKDIR /tmp/build
COPY requirements-andrius_sci_rep.txt /tmp/build/requirements-andrius_sci_rep.txt
RUN set -eux; \
    conda create -y -n andrius python=3.6; \
    conda run -n andrius conda install -y --file /tmp/build/requirements-andrius_sci_rep.txt

#RUN mkdir -p ~/miniconda3 \
#    && wget https://repo.anaconda.com/miniconda/Miniconda3-py37_23.1.0-1-Linux-x86_64.sh -O ~/miniconda3/miniconda.sh \
#    && bash ~/miniconda3/miniconda.sh -b -u -p ~/miniconda3 \
#    && rm ~/miniconda3/miniconda.sh \
#    && source ~/miniconda3/bin/activate \
#    && conda create --name andrius python=3.6 \
#    && conda activate andrius \
#    && conda install --yes --file requirements-andrius_sci_rep.txt \

#USER vscode
#RUN mkdir -p "${HOME}/miniconda" && \
#    bash /tmp/miniconda.sh -b -p "${HOME}/miniconda"
#ENV PATH="${HOME}/miniconda/bin:${PATH}"
#RUN . activate && conda create --name andrius python=3.6 && conda activate andrius && conda install --yes --file requirements-andrius_sci_rep.txt

# Add meta-data
LABEL org.opencontainers.image.version="v26.07.03" \
      org.opencontainers.image.authors="Alex Casson <alex.casson@manchester.ac.uk>" \
      org.opencontainers.image.title="Main programming dockerfile" \
      org.opencontainers.image.source="https://github.com/ALEX-CASSON-LAB/dockerfiles/dockerfile_main" \
      org.opencontainers.image.description="Python, Rust, and C/C++ container for general use" \
      org.opencontainers.image.licenses="MIT"
